/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.C_Kripto;
import java.awt.event.KeyEvent;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JRadioButton;
import javax.swing.JTextArea;
import javax.swing.JTextField;

import ErrorHandler.H_Error;
import java.awt.BorderLayout;
import javax.swing.JTable;

/**
 *
 * @author Raynald Krisnawan
 */
public class UI_Kriptografi extends javax.swing.JFrame {
    C_Kripto C_UI;
    public String algorithm;

    /**
     * Creates new form UI_Kriptografi
     */
    public UI_Kriptografi(String algorithm) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.R_encode.setSelected(true);
        this.algorithm = algorithm;
        C_UI = new C_Kripto(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Rmode = new javax.swing.ButtonGroup();
        L_Judul = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        R_encode = new javax.swing.JRadioButton();
        R_decode = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextArea1 = new javax.swing.JTextArea();
        L_Atas = new javax.swing.JLabel();
        L_Bawah = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TextArea2 = new javax.swing.JTextArea();
        submit = new javax.swing.JButton();
        B_Back = new javax.swing.JButton();
        TKey = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        L_Bawah1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        T_Langkah = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        L_Judul.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        L_Judul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L_Judul.setText("Judul");

        jLabel1.setText("Mode :");

        Rmode.add(R_encode);
        R_encode.setText("Encode");
        R_encode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R_encodeActionPerformed(evt);
            }
        });

        Rmode.add(R_decode);
        R_decode.setText("Decode");
        R_decode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R_decodeActionPerformed(evt);
            }
        });

        TextArea1.setColumns(20);
        TextArea1.setRows(5);
        jScrollPane1.setViewportView(TextArea1);

        L_Atas.setText("Plain-Text :");

        L_Bawah.setText("Cipher-Text :");

        TextArea2.setEditable(false);
        TextArea2.setColumns(20);
        TextArea2.setRows(5);
        jScrollPane2.setViewportView(TextArea2);

        submit.setText("Encode");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        B_Back.setText("BACK");
        B_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_BackActionPerformed(evt);
            }
        });

        TKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TKeyActionPerformed(evt);
            }
        });
        TKey.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TKeyKeyPressed(evt);
            }
        });

        jLabel5.setText("Key :");

        L_Bawah1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L_Bawah1.setText("Langkah");

        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);

        T_Langkah.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(T_Langkah);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(L_Judul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(R_encode, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(R_decode, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(L_Bawah, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(L_Atas, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(75, 75, 75)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TKey, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(156, 156, 156))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(B_Back, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(L_Bawah1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(178, 178, 178)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(L_Judul, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(R_encode)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(R_decode)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(L_Bawah1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B_Back, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(L_Atas, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TKey, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(82, 82, 82)
                                        .addComponent(L_Bawah, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(110, 110, 110))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void R_encodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R_encodeActionPerformed
        C_UI.C_RadioButtonE();
    }//GEN-LAST:event_R_encodeActionPerformed

    private void B_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_BackActionPerformed
        // TODO add your handling code here:
        this.dispose();
        UI_Menu new_UI = new UI_Menu();
        new_UI.setVisible(true);
    }//GEN-LAST:event_B_BackActionPerformed

    private void TKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TKeyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TKeyActionPerformed

    private void R_decodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R_decodeActionPerformed
        // TODO add your handling code here:
        C_UI.C_RadioButtonD();
    }//GEN-LAST:event_R_decodeActionPerformed

    private void TKeyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TKeyKeyPressed
        // TODO add your handling code here:
        // LIMIT 1
        // if (algorithm == C_Kripto.ALGO_XOR) {
        //     if (TKey.getText().length() >= 1 && !(evt.getKeyCode() == KeyEvent.VK_BACK_SPACE)){
        //         TKey.setEditable(false);
        //         H_Error.LimitField();
        //     }
        //     else{
        //         TKey.setEditable(true);
        //     }
        // }
        if (algorithm == C_Kripto.ALGO_RAIL || algorithm == C_Kripto.ALGO_SCYTALE){
            if (evt.getKeyChar() >= '1' && evt.getKeyChar() <= '9' || evt.getKeyCode() == KeyEvent.VK_BACK_SPACE) {
               TKey.setEditable(true);
            }
            else if(evt.getKeyChar() == '0'){
                TKey.setEditable(false);
                H_Error.zeroKey(); 
            }
            else{
                TKey.setEditable(false);
                H_Error.notInt(); 
            }
        }
        else if (algorithm == C_Kripto.ALGO_SUPER){
            if (evt.getKeyChar() >= '1' && evt.getKeyChar() <= '9' || evt.getKeyCode() == KeyEvent.VK_BACK_SPACE) {
               TKey.setEditable(true);
            }
            else if(evt.getKeyChar() == '0'){
                TKey.setEditable(false);
                H_Error.zeroKey(); 
            }
            else{
                TKey.setEditable(false);
                H_Error.notInt(); 
            } 
        }
        
    }//GEN-LAST:event_TKeyKeyPressed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
        if(TKey.getText().isEmpty()){
            H_Error.empty_key();
        }
        else{
            C_UI.buttonPressed();
        }
    }//GEN-LAST:event_submitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI_Kriptografi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI_Kriptografi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI_Kriptografi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI_Kriptografi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI_Kriptografi("XOR").setVisible(true);
            }
        });
    }

    public JLabel getL_Atas() {
        return L_Atas;
    }

    public void setL_Atas(JLabel L_Atas) {
        this.L_Atas = L_Atas;
    }

    public JLabel getL_Bawah() {
        return L_Bawah;
    }

    public void setL_Bawah(JLabel L_Bawah) {
        this.L_Bawah = L_Bawah;
    }

    public JLabel getL_Judul() {
        return L_Judul;
    }

    public void setL_Judul(JLabel L_Judul) {
        this.L_Judul = L_Judul;
    }

    public JRadioButton getM_decode() {
        return R_decode;
    }

    public void setM_decode(JRadioButton M_decode) {
        this.R_decode = M_decode;
    }

    public JRadioButton getM_encode() {
        return R_encode;
    }

    public void setM_encode(JRadioButton M_encode) {
        this.R_encode = M_encode;
    }

    public ButtonGroup getRmode() {
        return Rmode;
    }

    public void setRmode(ButtonGroup Rmode) {
        this.Rmode = Rmode;
    }

    public JTextField getTKey() {
        return TKey;
    }

    public void setTKey(JTextField TKey) {
        this.TKey = TKey;
    }

    public JTextArea getTextArea1() {
        return TextArea1;
    }

    public void setTextArea1(JTextArea TextArea1) {
        this.TextArea1 = TextArea1;
    }

    public JTextArea getTextArea2() {
        return TextArea2;
    }

    public void setTextArea2(JTextArea TextArea2) {
        this.TextArea2 = TextArea2;
    }

    public JButton getjButton2() {
        return B_Back;
    }

    public void setjButton2(JButton jButton2) {
        this.B_Back = jButton2;
    }

    public JButton getSubmit() {
        return submit;
    }

    public void setSubmit(JButton submit) {
        this.submit = submit;
    }

    public JTable getT_Langkah() {
        return T_Langkah;
    }

    public void setT_Langkah(JTable T_Langkah) {
        this.T_Langkah = T_Langkah;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_Back;
    private javax.swing.JLabel L_Atas;
    private javax.swing.JLabel L_Bawah;
    private javax.swing.JLabel L_Bawah1;
    private javax.swing.JLabel L_Judul;
    private javax.swing.JRadioButton R_decode;
    private javax.swing.JRadioButton R_encode;
    private javax.swing.ButtonGroup Rmode;
    private javax.swing.JTextField TKey;
    private javax.swing.JTable T_Langkah;
    private javax.swing.JTextArea TextArea1;
    private javax.swing.JTextArea TextArea2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables
}
